In [15]:
from itertools import combinations as cmb
import numpy as np

# たこ焼きの個数Nを取得
N = int(input())

# 各たこ焼きの味を取得
d = list(map(int, input().split()))

# たこ焼きの全組み合わせを作り、xとyに分離させる
x, y = np.array(list(cmb(d, 2))).T

# 体力の回復量の総和を求めて表示
print(np.sum(x*y))

 7
 5 0 7 8 3 3 2


312


In [ ]:
from itertools import combinations as cmb
import numpy as np

# たこ焼きの個数Nを取得
N = int(input())

# 各たこ焼きの味を取得
d = list(map(int, input().split()))

# たこ焼きの全組み合わせを作り、xとyに分離させる
ds = np.array(list(cmb(d, 2)))
dot_ds = np.apply_along_axis(lambda x: x[0]*x[1], 1, ds)

# 体力の回復量の総和を求めて表示
print(np.sum(dot_ds))

In [16]:
np.array(list(cmb(d, 2)))[:, 0]

array([5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 7, 7, 7, 7, 8, 8, 8, 3, 3, 3])

In [18]:
np.array(list(cmb(d, 2)))[:, 1]

array([0, 7, 8, 3, 3, 2, 7, 8, 3, 3, 2, 8, 3, 3, 2, 3, 3, 2, 3, 2, 2])

In [21]:
ds = np.array(list(cmb(d, 2)))

In [24]:
ds

array([[5, 0],
       [5, 7],
       [5, 8],
       [5, 3],
       [5, 3],
       [5, 2],
       [0, 7],
       [0, 8],
       [0, 3],
       [0, 3],
       [0, 2],
       [7, 8],
       [7, 3],
       [7, 3],
       [7, 2],
       [8, 3],
       [8, 3],
       [8, 2],
       [3, 3],
       [3, 2],
       [3, 2]])

In [26]:
ds.T

array([ 0, 35, 40, 15, 15, 10,  0,  0,  0,  0,  0, 56, 21, 21, 14, 24, 24,
       16,  9,  6,  6])

In [23]:
np.apply_along_axis(lambda x: x[0]*x[1], 1, ds)

array([ 0, 35, 40, 15, 15, 10,  0,  0,  0,  0,  0, 56, 21, 21, 14, 24, 24,
       16,  9,  6,  6])